package pokemon;

import java.util.HashMap;
import java.util.Map;

public class TypeCompatibility {
	private Map<String, Map<String, Double>> typeChart = new HashMap<>();

	public Map<String, Map<String, Double>> getTypeChart() {
		return typeChart;
	}

	public void setTypeChart() {
		Type normal = new Type("ノーマル");
		Type fire = new Type("ほのお");
		Type water = new Type("みず");
		Type electric = new Type("でんき");
		Type grass = new Type("くさ");
		Type ice = new Type("こおり");
		Type fighting = new Type("かくとう");
		Type poison = new Type("どく");
		Type ground = new Type("じめん");
		Type flying = new Type("ひこう");
		Type psychic = new Type("エスパー");
		Type bug = new Type("むし");
		Type rock = new Type("いわ");
		Type ghost = new Type("ゴースト");
		Type dragon = new Type("ドラゴン");
		Type dark = new Type("あく");
		Type steel = new Type("はがね");
		Type fairy = new Type("フェアリー");
		Type type = new Type("null");
		Map<String, Double> normalCom = new HashMap<>();
		normalCom.put(normal.getType(), 1.0);
		normalCom.put(fire.getType(), 1.0);
		normalCom.put(water.getType(), 1.0);
		normalCom.put(electric.getType(), 1.0);
		normalCom.put(grass.getType(), 1.0);
		normalCom.put(ice.getType(), 1.0);
		normalCom.put(fighting.getType(), 1.0);
		normalCom.put(poison.getType(), 1.0);
		normalCom.put(ground.getType(), 1.0);
		normalCom.put(flying.getType(), 1.0);
		normalCom.put(psychic.getType(), 1.0);
		normalCom.put(bug.getType(), 1.0);
		normalCom.put(rock.getType(), 0.5);
		normalCom.put(ghost.getType(), 0.0);
		normalCom.put(dragon.getType(), 1.0);
		normalCom.put(dark.getType(), 1.0);
		normalCom.put(steel.getType(), 0.5);
		normalCom.put(fairy.getType(), 1.0);
		normalCom.put(type.getType(), 1.0);
		typeChart.put(normal.getType(),normalCom);
		Map<String, Double> fireCom = new HashMap<>();
		fireCom.put(normal.getType(), 1.0);
		fireCom.put(fire.getType(), 0.5);
		fireCom.put(water.getType(), 0.5);
		fireCom.put(electric.getType(), 1.0);
		fireCom.put(grass.getType(), 2.0);
		fireCom.put(ice.getType(), 2.0);
		fireCom.put(fighting.getType(), 1.0);
		fireCom.put(poison.getType(), 1.0);
		fireCom.put(ground.getType(), 1.0);
		fireCom.put(flying.getType(), 1.0);
		fireCom.put(psychic.getType(), 1.0);
		fireCom.put(bug.getType(), 2.0);
		fireCom.put(rock.getType(), 0.5);
		fireCom.put(ghost.getType(), 1.0);
		fireCom.put(dragon.getType(), 0.5);
		fireCom.put(dark.getType(), 1.0);
		fireCom.put(steel.getType(), 2.0);
		fireCom.put(fairy.getType(), 1.0);
		fireCom.put(type.getType(), 1.0);
		typeChart.put(fire.getType(),fireCom);
		Map<String, Double> waterCom = new HashMap<>();
		waterCom.put(normal.getType(), 1.0);
		waterCom.put(fire.getType(), 2.0);
		waterCom.put(water.getType(), 0.5);
		waterCom.put(electric.getType(), 1.0);
		waterCom.put(grass.getType(), 0.5);
		waterCom.put(ice.getType(), 1.0);
		waterCom.put(fighting.getType(), 1.0);
		waterCom.put(poison.getType(), 1.0);
		waterCom.put(ground.getType(), 2.0);
		waterCom.put(flying.getType(), 1.0);
		waterCom.put(psychic.getType(), 1.0);
		waterCom.put(bug.getType(), 1.0);
		waterCom.put(rock.getType(), 2.0);
		waterCom.put(ghost.getType(), 1.0);
		waterCom.put(dragon.getType(), 0.5);
		waterCom.put(dark.getType(), 1.0);
		waterCom.put(steel.getType(), 1.0);
		waterCom.put(fairy.getType(), 1.0);
		waterCom.put(type.getType(), 1.0);
		typeChart.put(water.getType(),waterCom);
		Map<String, Double> electricCom = new HashMap<>();
		electricCom.put(normal.getType(), 1.0);
		electricCom.put(fire.getType(), 1.0);
		electricCom.put(water.getType(), 2.0);
		electricCom.put(electric.getType(), 0.5);
		electricCom.put(grass.getType(), 0.5);
		electricCom.put(ice.getType(), 1.0);
		electricCom.put(fighting.getType(), 1.0);
		electricCom.put(poison.getType(), 1.0);
		electricCom.put(ground.getType(), 0.0);
		electricCom.put(flying.getType(), 2.0);
		electricCom.put(psychic.getType(), 1.0);
		electricCom.put(bug.getType(), 1.0);
		electricCom.put(rock.getType(), 1.0);
		electricCom.put(ghost.getType(), 1.0);
		electricCom.put(dragon.getType(), 0.5);
		electricCom.put(dark.getType(), 1.0);
		electricCom.put(steel.getType(), 1.0);
		electricCom.put(fairy.getType(), 1.0);
		electricCom.put(type.getType(), 1.0);
		typeChart.put(electric.getType(),electricCom);
		Map<String, Double>grassCom = new HashMap<>();
		grassCom.put(normal.getType(), 1.0);
		grassCom.put(fire.getType(), 0.5);
		grassCom.put(water.getType(), 2.0);
		grassCom.put(electric.getType(), 1.0);
		grassCom.put(grass.getType(), 0.5);
		grassCom.put(ice.getType(), 1.0);
		grassCom.put(fighting.getType(), 1.0);
		grassCom.put(poison.getType(), 0.5);
		grassCom.put(ground.getType(), 2.0);
		grassCom.put(flying.getType(), 0.5);
		grassCom.put(psychic.getType(), 1.0);
		grassCom.put(bug.getType(), 0.5);
		grassCom.put(rock.getType(), 2.0);
		grassCom.put(ghost.getType(), 1.0);
		grassCom.put(dragon.getType(), 0.5);
		grassCom.put(dark.getType(), 1.0);
		grassCom.put(steel.getType(), 0.5);
		grassCom.put(fairy.getType(), 1.0);
		grassCom.put(type.getType(), 1.0);
		typeChart.put(grass.getType(),grassCom);
		Map<String, Double> iceCom = new HashMap<>();
		iceCom.put(normal.getType(), 1.0);
		iceCom.put(fire.getType(), 0.5);
		iceCom.put(water.getType(), 0.5);
		iceCom.put(electric.getType(), 1.0);
		iceCom.put(grass.getType(), 2.0);
		iceCom.put(ice.getType(), 0.5);
		iceCom.put(fighting.getType(), 1.0);
		iceCom.put(poison.getType(), 1.0);
		iceCom.put(ground.getType(), 2.0);
		iceCom.put(flying.getType(), 2.0);
		iceCom.put(psychic.getType(), 1.0);
		iceCom.put(bug.getType(), 1.0);
		iceCom.put(rock.getType(), 1.0);
		iceCom.put(ghost.getType(), 1.0);
		iceCom.put(dragon.getType(), 2.0);
		iceCom.put(dark.getType(), 1.0);
		iceCom.put(steel.getType(), 0.5);
		iceCom.put(fairy.getType(), 1.0);
		iceCom.put(type.getType(), 1.0);
		typeChart.put(ice.getType(),iceCom);
		Map<String, Double> fightingCom = new HashMap<>();
		fightingCom.put(normal.getType(), 2.0);
		fightingCom.put(fire.getType(), 1.0);
		fightingCom.put(water.getType(), 1.0);
		fightingCom.put(electric.getType(), 1.0);
		fightingCom.put(grass.getType(), 1.0);
		fightingCom.put(ice.getType(), 2.0);
		fightingCom.put(fighting.getType(), 1.0);
		fightingCom.put(poison.getType(), 1.0);
		fightingCom.put(ground.getType(), 1.0);
		fightingCom.put(flying.getType(), 0.5);
		fightingCom.put(psychic.getType(), 0.5);
		fightingCom.put(bug.getType(), 0.5);
		fightingCom.put(rock.getType(), 2.0);
		fightingCom.put(ghost.getType(), 0.0);
		fightingCom.put(dragon.getType(), 1.0);
		fightingCom.put(dark.getType(), 2.0);
		fightingCom.put(steel.getType(), 2.0);
		fightingCom.put(fairy.getType(), 0.5);
		fightingCom.put(type.getType(), 1.0);
		typeChart.put(fighting.getType(),fightingCom);
		Map<String, Double> poisonCom = new HashMap<>();
		poisonCom.put(normal.getType(), 1.0);
		poisonCom.put(fire.getType(), 1.0);
		poisonCom.put(water.getType(), 1.0);
		poisonCom.put(electric.getType(), 1.0);
		poisonCom.put(grass.getType(), 2.0);
		poisonCom.put(ice.getType(), 1.0);
		poisonCom.put(fighting.getType(), 1.0);
		poisonCom.put(poison.getType(), 0.5);
		poisonCom.put(ground.getType(), 0.5);
		poisonCom.put(flying.getType(), 1.0);
		poisonCom.put(psychic.getType(), 1.0);
		poisonCom.put(bug.getType(), 1.0);
		poisonCom.put(rock.getType(), 0.5);
		poisonCom.put(ghost.getType(), 0.5);
		poisonCom.put(dragon.getType(), 1.0);
		poisonCom.put(dark.getType(), 1.0);
		poisonCom.put(steel.getType(), 0.0);
		poisonCom.put(fairy.getType(), 2.0);
		poisonCom.put(type.getType(), 1.0);
		typeChart.put(poison.getType(),poisonCom);
		Map<String, Double> groundCom = new HashMap<>();
		groundCom.put(normal.getType(), 1.0);
		groundCom.put(fire.getType(), 2.0);
		groundCom.put(water.getType(), 1.0);
		groundCom.put(electric.getType(), 2.0);
		groundCom.put(grass.getType(), 0.5);
		groundCom.put(ice.getType(), 1.0);
		groundCom.put(fighting.getType(), 1.0);
		groundCom.put(poison.getType(), 2.0);
		groundCom.put(ground.getType(), 1.0);
		groundCom.put(flying.getType(), 0.0);
		groundCom.put(psychic.getType(), 1.0);
		groundCom.put(bug.getType(), 0.5);
		groundCom.put(rock.getType(), 2.0);
		groundCom.put(ghost.getType(), 1.0);
		groundCom.put(dragon.getType(), 1.0);
		groundCom.put(dark.getType(), 1.0);
		groundCom.put(steel.getType(), 2.0);
		groundCom.put(fairy.getType(), 1.0);
		groundCom.put(type.getType(), 1.0);
		typeChart.put(ground.getType(),groundCom);
		Map<String, Double> flyingCom = new HashMap<>();
		flyingCom.put(normal.getType(), 1.0);
		flyingCom.put(fire.getType(), 1.0);
		flyingCom.put(water.getType(), 1.0);
		flyingCom.put(electric.getType(), 0.5);
		flyingCom.put(grass.getType(), 2.0);
		flyingCom.put(ice.getType(), 1.0);
		flyingCom.put(fighting.getType(), 2.0);
		flyingCom.put(poison.getType(), 1.0);
		flyingCom.put(ground.getType(), 1.0);
		flyingCom.put(flying.getType(), 1.0);
		flyingCom.put(psychic.getType(), 1.0);
		flyingCom.put(bug.getType(), 2.0);
		flyingCom.put(rock.getType(), 0.5);
		flyingCom.put(ghost.getType(), 1.0);
		flyingCom.put(dragon.getType(), 1.0);
		flyingCom.put(dark.getType(), 1.0);
		flyingCom.put(steel.getType(), 0.5);
		flyingCom.put(fairy.getType(), 1.0);
		flyingCom.put(type.getType(), 1.0);
		typeChart.put(flying.getType(),flyingCom);
		Map<String, Double> psychicCom = new HashMap<>();
		psychicCom.put(normal.getType(), 1.0);
		psychicCom.put(fire.getType(), 1.0);
		psychicCom.put(water.getType(), 1.0);
		psychicCom.put(electric.getType(), 1.0);
		psychicCom.put(grass.getType(), 1.0);
		psychicCom.put(ice.getType(), 1.0);
		psychicCom.put(fighting.getType(), 2.0);
		psychicCom.put(poison.getType(), 2.0);
		psychicCom.put(ground.getType(), 1.0);
		psychicCom.put(flying.getType(), 1.0);
		psychicCom.put(psychic.getType(), 1.0);
		psychicCom.put(bug.getType(), 0.5);
		psychicCom.put(rock.getType(), 1.0);
		psychicCom.put(ghost.getType(), 1.0);
		psychicCom.put(dragon.getType(), 1.0);
		psychicCom.put(dark.getType(), 0.0);
		psychicCom.put(steel.getType(), 0.5);
		psychicCom.put(fairy.getType(), 1.0);
		psychicCom.put(type.getType(), 1.0);
		typeChart.put(psychic.getType(),psychicCom);
		Map<String, Double> bugCom = new HashMap<>();
		bugCom.put(normal.getType(), 1.0);
		bugCom.put(fire.getType(), 0.5);
		bugCom.put(water.getType(), 1.0);
		bugCom.put(electric.getType(), 1.0);
		bugCom.put(grass.getType(), 2.0);
		bugCom.put(ice.getType(), 1.0);
		bugCom.put(fighting.getType(), 0.5);
		bugCom.put(poison.getType(), 0.5);
		bugCom.put(ground.getType(), 1.0);
		bugCom.put(flying.getType(), 0.5);
		bugCom.put(psychic.getType(), 2.0);
		bugCom.put(bug.getType(), 1.0);
		bugCom.put(rock.getType(), 1.0);
		bugCom.put(ghost.getType(), 1.0);
		bugCom.put(dragon.getType(), 1.0);
		bugCom.put(dark.getType(), 2.0);
		bugCom.put(steel.getType(), 0.5);
		bugCom.put(fairy.getType(), 0.5);
		bugCom.put(type.getType(), 1.0);
		typeChart.put(bug.getType(),bugCom);
		Map<String, Double> rockCom = new HashMap<>();
		rockCom.put(normal.getType(), 1.0);
		rockCom.put(fire.getType(), 2.0);
		rockCom.put(water.getType(), 1.0);
		rockCom.put(electric.getType(), 1.0);
		rockCom.put(grass.getType(), 1.0);
		rockCom.put(ice.getType(), 2.0);
		rockCom.put(fighting.getType(), 0.5);
		rockCom.put(poison.getType(), 1.0);
		rockCom.put(ground.getType(), 0.5);
		rockCom.put(flying.getType(), 2.0);
		rockCom.put(psychic.getType(), 1.0);
		rockCom.put(bug.getType(), 2.0);
		rockCom.put(rock.getType(), 1.0);
		rockCom.put(ghost.getType(), 1.0);
		rockCom.put(dragon.getType(), 1.0);
		rockCom.put(dark.getType(), 1.0);
		rockCom.put(steel.getType(), 0.5);
		rockCom.put(fairy.getType(), 1.0);
		rockCom.put(type.getType(), 1.0);
		typeChart.put(rock.getType(),rockCom);
		Map<String, Double> ghostCom = new HashMap<>();
		ghostCom.put(normal.getType(), 0.0);
		ghostCom.put(fire.getType(), 1.0);
		ghostCom.put(water.getType(), 1.0);
		ghostCom.put(electric.getType(), 1.0);
		ghostCom.put(grass.getType(), 1.0);
		ghostCom.put(ice.getType(), 1.0);
		ghostCom.put(fighting.getType(), 1.0);
		ghostCom.put(poison.getType(), 1.0);
		ghostCom.put(ground.getType(), 1.0);
		ghostCom.put(flying.getType(), 1.0);
		ghostCom.put(psychic.getType(), 1.0);
		ghostCom.put(bug.getType(), 1.0);
		ghostCom.put(rock.getType(), 1.0);
		ghostCom.put(ghost.getType(), 2.0);
		ghostCom.put(dragon.getType(), 1.0);
		ghostCom.put(dark.getType(), 0.5);
		ghostCom.put(steel.getType(), 1.0);
		ghostCom.put(fairy.getType(), 1.0);
		ghostCom.put(type.getType(), 1.0);
		typeChart.put(ghost.getType(),ghostCom);
		Map<String, Double> dragonCom = new HashMap<>();
		dragonCom.put(normal.getType(), 1.0);
		dragonCom.put(fire.getType(), 1.0);
		dragonCom.put(water.getType(), 1.0);
		dragonCom.put(electric.getType(), 1.0);
		dragonCom.put(grass.getType(), 1.0);
		dragonCom.put(ice.getType(), 1.0);
		dragonCom.put(fighting.getType(), 1.0);
		dragonCom.put(poison.getType(), 1.0);
		dragonCom.put(ground.getType(), 1.0);
		dragonCom.put(flying.getType(), 1.0);
		dragonCom.put(psychic.getType(), 1.0);
		dragonCom.put(bug.getType(), 1.0);
		dragonCom.put(rock.getType(), 1.0);
		dragonCom.put(ghost.getType(), 1.0);
		dragonCom.put(dragon.getType(), 2.0);
		dragonCom.put(dark.getType(), 1.0);
		dragonCom.put(steel.getType(), 0.5);
		dragonCom.put(fairy.getType(), 0.0);
		dragonCom.put(type.getType(), 1.0);
		typeChart.put(dragon.getType(),dragonCom);
		Map<String, Double> darkCom = new HashMap<>();
		darkCom.put(normal.getType(), 1.0);
		darkCom.put(fire.getType(), 1.0);
		darkCom.put(water.getType(), 1.0);
		darkCom.put(electric.getType(), 1.0);
		darkCom.put(grass.getType(), 1.0);
		darkCom.put(ice.getType(), 1.0);
		darkCom.put(fighting.getType(), 0.5);
		darkCom.put(poison.getType(), 1.0);
		darkCom.put(ground.getType(), 1.0);
		darkCom.put(flying.getType(), 1.0);
		darkCom.put(psychic.getType(), 2.0);
		darkCom.put(bug.getType(), 1.0);
		darkCom.put(rock.getType(), 1.0);
		darkCom.put(ghost.getType(), 2.0);
		darkCom.put(dragon.getType(), 1.0);
		darkCom.put(dark.getType(), 0.5);
		darkCom.put(steel.getType(), 1.0);
		darkCom.put(fairy.getType(), 0.5);
		darkCom.put(type.getType(), 1.0);
		typeChart.put(dark.getType(),darkCom);
		Map<String, Double> steelCom = new HashMap<>();
		steelCom.put(normal.getType(), 1.0);
		steelCom.put(fire.getType(), 0.5);
		steelCom.put(water.getType(), 0.5);
		steelCom.put(electric.getType(), 0.5);
		steelCom.put(grass.getType(), 1.0);
		steelCom.put(ice.getType(), 2.0);
		steelCom.put(fighting.getType(), 1.0);
		steelCom.put(poison.getType(), 1.0);
		steelCom.put(ground.getType(), 1.0);
		steelCom.put(flying.getType(), 1.0);
		steelCom.put(psychic.getType(), 1.0);
		steelCom.put(bug.getType(), 1.0);
		steelCom.put(rock.getType(), 2.0);
		steelCom.put(ghost.getType(), 1.0);
		steelCom.put(dragon.getType(), 1.0);
		steelCom.put(dark.getType(), 1.0);
		steelCom.put(steel.getType(), 0.5);
		steelCom.put(fairy.getType(), 2.0);
		steelCom.put(type.getType(), 1.0);
		typeChart.put(steel.getType(),steelCom);
		Map<String, Double> fairyCom = new HashMap<>();
		fairyCom.put(normal.getType(), 1.0);
		fairyCom.put(fire.getType(), 0.5);
		fairyCom.put(water.getType(), 1.0);
		fairyCom.put(electric.getType(), 1.0);
		fairyCom.put(grass.getType(), 1.0);
		fairyCom.put(ice.getType(), 1.0);
		fairyCom.put(fighting.getType(), 2.0);
		fairyCom.put(poison.getType(), 1.0);
		fairyCom.put(ground.getType(), 1.0);
		fairyCom.put(flying.getType(), 1.0);
		fairyCom.put(psychic.getType(), 1.0);
		fairyCom.put(bug.getType(), 1.0);
		fairyCom.put(rock.getType(), 1.0);
		fairyCom.put(ghost.getType(), 1.0);
		fairyCom.put(dragon.getType(), 2.0);
		fairyCom.put(dark.getType(), 2.0);
		fairyCom.put(steel.getType(), 0.5);
		fairyCom.put(fairy.getType(), 1.0);
		fairyCom.put(type.getType(), 1.0);
		typeChart.put(fairy.getType(),fairyCom);
	}
}
